fully bootstrapped server
 On branch usr

	modified:   docs/create-devbox.md
	new file:   usr/configs/rsync-exclude.list
	renamed:    usr/libexec/jfd-build-devbox -> usr/libexec/jfd-bootstrap-server
	modified:   usr/libexec/jfd-deploy
	modified:   usr/libexec/jfd-install
	modified:   usr/libexec/lib/utils.sh
	new file:   virtual_machines/devbox/toehold.sh

diff --git a/usr/libexec/jfd-bootstrap-server b/usr/libexec/jfd-bootstrap-server
--- a/usr/libexec/jfd-bootstrap-server
+++ b/usr/libexec/jfd-bootstrap-server
@@ -10,10 +10,23 @@ source "$_JFD_LIB/utils.sh"
 jfd="$_JFD_ROOT/bin/jfd"
 main () {
     not_local "You probably don't want to run this script on your workstation."
+
     jfd update-system
     sudo apt-get install build-essential --assume-yes
-    jfd install ruby
-    sudo gem install chef --no-ri --no-rdoc
+
+    jfd install ruby || fail "Unable to install Ruby"
+
+    if ! [ $(command -v chef-solo) ]; then
+        sudo gem install chef --no-ri --no-rdoc || \
+            fail "Unable to install chef."
+    fi
+
+    if ! [ -d "/build" ]; then
+        sudo mkdir -p -- "/build" ||  \
+            fail "Unable to create /build directory"
+    fi
+
+    sudo chown vagrant:vagrant "/build"
 }
 
 main $@
diff --git a/usr/libexec/jfd-install b/usr/libexec/jfd-install
--- a/usr/libexec/jfd-install
+++ b/usr/libexec/jfd-install
@@ -41,17 +41,19 @@ install_ruby () {
         sudo rm -rf /opt/vagrant_ruby
     fi
 
-    if ! [ -d "$RUBYDIR" ]; then
-        ensure_dir "$RUBYDIR"
-        curl -# -L "$url" \
-            | tar xzf - -C "$RUBYDIR" --strip-components=1 \
-            || fail "Could not download RubyGems"
+    if ! [ $(command -v gem) ]; then
+        if ! [ -d "$RUBYDIR" ]; then
+            ensure_dir "$RUBYDIR"
+            curl -# -L "$url" \
+                | tar xzf - -C "$RUBYDIR" --strip-components=1 \
+                || fail "Could not download RubyGems"
+        fi
+
+        cd "$RUBYDIR"
+        sudo ruby setup.rb --no-format-executable
+
+        rm -rf "$RUBYDIR"
     fi
-
-    cd "$RUBYDIR"
-    sudo ruby setup.rb --no-format-executable
-
-    rm -rf "$RUBYDIR"
 }
 
 main $@
