deploy new remote machine
 On branch master

	modified:   docs/create-remotebox.md
	modified:   remote/libexec/lib/pyutil.py
	modified:   remote/libexec/lib/utils.sh
	modified:   remote/libexec/remote-install-system
	modified:   remote/libexec/remote-setup

diff --git a/remote/libexec/remote-install-system b/remote/libexec/remote-install-system
--- a/remote/libexec/remote-install-system
+++ b/remote/libexec/remote-install-system
@@ -4,6 +4,8 @@
 # Help: This script is only meant to be run on a virtual machine, never your
 # local workstation or laptop.
 
+NODE_VERSION="v0.10.4"
+
 source $_REMOTE_UTILS
 
 no_super_user "for install-system script."
@@ -18,7 +20,7 @@ sudo apt-get dist-upgrade --assume-yes || fail "Unable to upgrade the system."
 # curl - Utiility
 # vim - Utiility
 # tree - Utiility
-# build-essential - Required for VirtualBox
+# build-essential - Required for VirtualBox and Node.js
 # dkms - Required for VirtualBox
 # python-software-properties - Required for latest NGINX.
 
@@ -26,6 +28,7 @@ sudo apt-get --assume-yes install \
     curl \
     vim \
     tree \
+    build-essential \
     python-software-properties \
     || fail "Unable to install system dependencies."
 
@@ -54,6 +57,32 @@ sudo apt-get --assume-yes install \
     php5-curl \
     php5-cli \
     || fail "Unable to install application packages."
+
+# Install Node.js
+echo "Checking for Node.js ..."
+if [ "$( node --version )" != "$NODE_VERSION" ]; then
+	echo "Installing Node.js $NODE_VERSION"
+
+	nodeurl="http://nodejs.org/dist/$NODE_VERSION/node-$NODE_VERSION.tar.gz"
+	echo "Fetching Node.js from $nodeurl"
+
+	mkdir "/tmp/node_install"
+
+	curl -# -L "$nodeurl" \
+			| tar xzf - -C "/tmp/node_install" --strip-components=1 \
+			|| fail "Could not download Node.js $NODE_VERSION"
+
+	cd "/tmp/node_install"
+	"./configure" || fail "Unable to configure Node.js"
+	make || fail "Unable to make Node.js"
+	sudo make install || fail "Unable to install Node.js"
+
+	cd "$HOME"
+	rm -rf "/tmp/node_install"
+	echo "Node.js $NODE_VERSION installed."
+else
+	echo "Node.js $( node --version ) already installed."
+fi
 
 # Create the socket directory for PHP-FPM.
 if ! [ -d /var/run/php5-fpm ]; then
